# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name PersistenceLandscape
#' @aliases Rcpp_PersistenceLandscape-class
#' @title Exported C++ Class 'PersistenceLandscape'
#' @description Export, and create and manipulate objects of, the
#'   PersistenceLandscape' C++ class.
#' @details The C++ class 'PersistenceLandscape' is exposed as the S4 class
#'   'Rcpp_PersistenceLandscape' via the `RCPP_MODULE()` macro provided by
#'   **[Rcpp][Rcpp::Rcpp-package]**. See
#'   <https://github.com/coatless-rd-rcpp/rcpp-modules-student> for an
#'   introduction. New objects should be created from persistence data
#'   (diagrams) using [pl_new()].
#' @field new Constructor.
#' @field exact Representation of the underlying PL.
#' @field min_x Infimum (left endpoint) of the support of a discrete PL.
#' @field max_x Supremum (right endpoint) of the support of a discrete PL.
#' @field dx Resolution of the representation of a discrete PL.
#' @seealso [pl_new()] for the R wrapper.
#' @example inst/examples/ex-PersistenceLandscape.R
#' @export
NULL

almostEqual <- function(a, b) {
    .Call(`_plt_almostEqual`, a, b)
}

almostUnique <- function(a) {
    .Call(`_plt_almostUnique`, a)
}

